# lst=[]
# for i in range(4):
#     name=input('enter name')
#     lst.append(name)
# for i in lst:
#     print(i)
print('............................')
# f=open('student.txt', mode='w')
# f.write('hi how r u')
# f.close()
# f = open('student.txt', mode='w')
# f.write('hello\n')
# f.write('how r u\n')
# f.write('what doing')
# f.close()
# print('writing sucess')
print('..............')
# f=open('student.txt', mode='r')
# data=f.read()
# print(data)
# f.close()
print('...................')
# f=open('student.txt', mode='rb')
# data=f.read()
# print(data)
# f.close()
# print('.........................')
# f= open('student.txt', mode='r', encoding='utf-8')
# print(f.name)
# print(f.mode)
# print(f.readable())
# print(f.writable())
# print(f.closed)
print('..........................')
# f=open('student.txt', mode='r+', encoding='utf-8')
# print(f.name)
# print(f.mode)
# print(f.readable())
# print(f.writable())
# f.close()
# print(f.closed)
#check file exists or not
# import os
# print(os.path.isfile('student.txt'))
# print('..................')
# import os
# if os.path.isfile('student.txt'):
#     f=open('student.txt')
#     print('file opened')
#     f.close()
# else:
#     print('file not found')
# print('.................')
# f= open('student.txt', mode='w')
# f.write('HELLO')
# f.close()

# f=open('student.txt', mode='w')
# n=f.write('hello\n')
# print(n)
# f.close()
#
# f=open('student.txt', mode='w')
# f.write('hi\n')
# f.write('hello\n')
# f.write('how r u')
# print(n)
# f.close()
# print('..........................')
# f=open('student1.txt', mode='x')
# f.write('hi\n')
# f.write('hello\n')
# f.write('how r u')
# f.close()
# print('........................')
# f=open('student.txt', mode='a')
# f.write('bye')
# f.close()
f=open('student.txt', mode='w')
lst=['welcometoIndia']                                   # lst=['raju\n', 'sonu\n', 'moju\n', 'boju\n']
f.writelines(lst)
f.close()
print('sucess')
# print('....................')
# f=open('student.txt', mode='r')
# data=f.read(12)
# print(data)
# print('completed!!!!!')
# print('.....................')
# f=open('student.txt', mode='r')
# data1=f.read(2)
# data2=f.read(2)
# print(data1)
# print(data2)
# f.close()
# print('completed')
# print('..........................')
# f=open('student.txt', mode='r')
# data1=f.readline()
# data2=f.readline()
# print(data1, end='')
# print(data2)
# f.close()
# print('...................')
# f=open('student.txt', mode='r')
# data=f.readlines()
# print(data)
# for i in data:
#     print(i)
# f.close()
# tell and seek
# f=open('student.txt', mode='r')
# print(f.tell())
# data1=f.read(4)
# print(data1)
# print(f.tell())
# data2=f.read(3)
# print(data2)
# print(f.tell())
print('......................')
# f=open('student.txt', mode='r')
# print(f.tell())
# f.seek(7)
# print(f.tell())
# data=f.read()
# print(data)
print('..................')
# f=open('student.txt', mode='r')
# print(f.tell())
# f.seek(7)
# print(f.tell())
# data1=f.read()
# print(data1)
# f.seek(2)
# print(f.tell())
# data2=f.read()
# print(data2)
print('.......................................')
# f=open('student.txt', mode='r+')
# data=f.read()
# f.write('youtube')
# print(data)
# print('...................')
# f=open('student.txt', mode='r+')
# print(f.tell())
# data=f.read()
# print(f.tell())
# f.write('youtube')
# print(f.tell())
# print(data)
# print(f.tell())
print('................................')
# f=open('student.txt', mode='w+')
# f.write('youtube')
# data=f.read()
# print(data)

# f=open('student.txt', mode='w+')
# print(f.tell())
# f.write('youtube')
# print(f.tell())
# f.seek(0)
# print(f.tell())
# data=f.read()
# print(f.tell())
# print(data)
print('..................')
# f=open('student.txt', mode='a+')
# print(f.tell())
# f.write('youtube')
# print(f.tell())
# f.seek(0)
# data=f.read()
# print(f.tell())
# print(data)
print('...................')
#copy file content
# f1=open('student.txt', mode='r')
# f2=open('student1.txt', mode='w')
# data=f1.read()
# f2.write(data)
# f1.close()
# f2.close()
with open('student.txt')as f:
    data=f.read()
    print(data)

print(f.closed)