# from time import time, ctime, localtime
# epoch = time()
# print(epoch)
#
# et = ctime(epoch)
# print(et)
# print(ctime()
print('...........................................')
from time import time, ctime, localtime
stobj=localtime()
print(stobj)
print(stobj.tm_year)
print("year:", stobj.tm_year)
print("month:", stobj.tm_mon)
print("date:", stobj.tm_mday)
print("hour:", stobj.tm_hour)
print("minute:", stobj.tm_min)
print("second:", stobj.tm_sec)
# creating object of datetime class
print('.............................')
from datetime import datetime
dt1=datetime(year=2022, month=9, day=19)
dt2=datetime(year=2021, month=5, day=29, hour=15, minute=33)
dt3=datetime(2014, 4, 25)
dt4=datetime(2016, 5, 24, 14, 30, 22)
print(dt1)
print(dt2)
print(dt3)
print(dt4)
print(dt1.year)
print(dt2.year)
print('.......................................................')
from datetime import datetime
# ct=datetime.today()
ct=datetime.now()
print(ct)
print(ct.day)
print('..............................................')
from datetime import date
d1=date(year=2022, month=9, day=19)
print(d1)
cd=date.today()
print(cd)
print(cd.year)
print('...................................................')
from datetime import time
t=time(hour=15, minute=25, second=55)
print(t)
print(t.minute)
print('.................................................')
#time delta class
from datetime import timedelta, date
td=timedelta(days=10)
d=date.today()
print(d+td)
print(d-td)
print('...................................')
#comparing two dates
from datetime import date
d1=date(2022, 5, 20)
d2=date(2020, 5, 22)
print(d1==d2)
print(d1>d2)
print(d1<d2)
print(d1!=d2)
print('..........................................')
#formatting date and time
from datetime import datetime, time
dt=datetime.today()
print(dt)
print('..............')
newd1=dt.strftime("%B%d, %y")
print(newd1)
print('..................')
newd2=dt.strftime("%d/%b/%y")
print(newd2)
print('.................')
newd3=dt.strftime("%d-%m-%y")
print(newd3)
print('.....................')

newt1=dt.strftime("%H:%M:%S")
print(newt1)
print('.............')
newt2=dt.strftime("%I:%M:%S")
print(newt2)
